repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff
        entry: uv run --native-tls ruff check --fix
        language: system
        types: [python]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: uv run --native-tls ruff format
        language: system
        types: [python]
        require_serial: true
      - id: pytest
        name: pytest
        entry: uv run --native-tls pytest --cov --cov-report=term-missing
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
